### ISSUE TITLE
Compile error (Visual Studio 2019) 64bit

### ISSUE THREAD

**Issue by Crandalius** [subsix-wow/KyrianCore-FREE#1]
Hello,

I keep getting the attached error when building this source, could you kindly give any advice to why this would happen?

Thanks

![Kyriancore](https://user-images.githubusercontent.com/26557039/121398131-50cdcd80-c955-11eb-8245-6956aa91ffb4.PNG)

**Comment by welder1976** [comment]
fix

**Comment by subsix-wow** [comment]
Thanks for report. @welder1976 fixed it.
